import { StyleSheet } from "react-native";
import { colors, radius } from "@/lib/theme";

export const formStyles = StyleSheet.create({
  field: { gap: 6 },
  label: { fontSize: 13, fontWeight: "500", color: colors.muted },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.foreground,
  },
  amountInput: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 26,
    fontWeight: "700",
    color: colors.foreground,
  },
  error: { fontSize: 13, color: colors.expense },
  buttonRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryButtonText: { color: colors.primaryForeground, fontSize: 16, fontWeight: "600" },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  dangerButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingVertical: 14,
    alignItems: "center",
  },
  dangerButtonText: { color: colors.expense, fontSize: 15, fontWeight: "600" },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: `${colors.primary}1a` },
  chipText: { fontSize: 14, color: colors.foreground },
  chipTextActive: { fontWeight: "600" },
  segmented: {
    flexDirection: "row",
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    padding: 4,
    gap: 4,
  },
  segmentBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: "center" },
  segmentBtnActive: { backgroundColor: colors.primary },
  segmentText: { fontSize: 14, fontWeight: "500", color: colors.muted },
  segmentTextActive: { color: colors.primaryForeground },
});
